version: '3'

services:
  api:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - "./config-test:/app/config"

  e2etests:
    depends_on:
      - api
    image: golang:buster
    command: /app/scripts/wait-for-it/wait-for-it.sh api:7000 -t 300 -- make -C /app e2etest-compose
    environment:
      CI: "true"
      api_host: "http://api:7000/"
    volumes:
      - .:/app
