name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/*
      - README.md
  pull_request:
    paths-ignore:
      - .github/workflows/*
      - README.md
env:
  GO_VERSION: 1.16

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run Tests
        run: |
          mkdir config
          echo "tokens:" >./config-test/config.yaml
          echo "  - "${{ secrets.CI_BOT_TOKEN_1 }}"" >> ./config-test/config.yaml
          echo "  - "${{ secrets.CI_BOT_TOKEN_2 }}"" >> ./config-test/config.yaml
          echo "  - "${{ secrets.CI_BOT_TOKEN_3 }}"" >> ./config-test/config.yaml
          echo "api_key: "" " >> ./config-test/config.yaml
          echo "chat_id: ${{ secrets.CI_CHAT_ID }}" >> ./config-test/config.yaml
          echo "draft_chat_id: ${{ secrets.CI_DRAFT_CHAT_ID }}" >> ./config-test/config.yaml
          make test
          chmod 777 ./scripts/wait-for-it/wait-for-it.sh
          make docker-e2etest
