name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/*
  pull_request:
    paths-ignore:
      - .github/workflows/*
env:
  GO_VERSION: 1.16

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run Tests
        run: |
          (
            echo BOT_TOKEN=${{ secrets.CI_BOT_TOKEN_1 }}
            echo BOT_TOKENS=${{ secrets.CI_BOT_TOKEN_1 }},${{ secrets.CI_BOT_TOKEN_2 }},${{ secrets.CI_BOT_TOKEN_3 }}
            echo TOKENS=${{ secrets.CI_BOT_TOKEN_1 }},${{ secrets.CI_BOT_TOKEN_2 }},${{ secrets.CI_BOT_TOKEN_3 }}
            echo DRAFT_CHAT_ID=${{ secrets.CI_DRAFT_CHAT_ID }}
            echo CHAT_ID=${{ secrets.CI_CHAT_ID }}
            ) > .env
          cp .env .env.test
          make test
          chmod 777 ./scripts/wait-for-it/wait-for-it.sh
          make docker-e2etest
